### ISSUE TITLE
Replay Buffer Builds Expired

### ISSUE THREAD

**Issue by Theray070696** [Penwy/adv-ff#3]
I know this isn't the right repo, but the [custom builds](https://github.com/Penwy/obs-studio/actions/runs/7074380931) with upstream PR 8955 included have expired

**Comment by Penwy** [comment]
Oh mb, didn't notice.
I'll do a new build with obs 30.1 today.

**Comment by Penwy** [comment]
There, changed the doc and release to include the new artifacts, ty for the head's up. :purple_heart:

**Comment by NullFragment** [comment]
It looks like they expired again, unfortunately. From what I could see on the PR it looks like everyone is okay with the changes for the most part, but there's a minor request to merge two of the commits and split one off.

**Comment by Penwy** [comment]
Yee. I'll re-do a build and take care of the merge conflict on the PR once I'm home

**Comment by barrelltitor** [comment]
Custom build link expired again
https://github.com/Penwy/obs-studio/actions/runs/5301025505

**Comment by Penwy** [comment]
custom builds are now distributed in the releases page and do not expire.
https://github.com/Penwy/adv-ff/releases/tag/1.2.0
