### ISSUE TITLE
does not work in obs 30.2.3, any workarounds?

### ISSUE THREAD

**Issue by ZappinZapper** [Penwy/adv-ff#7]
self-explanatory

**Comment by Penwy** [comment]
It is not self-explanatory, as it works on my end.
Can you detail a bit more, what you are doing, what you expect to happen, and what happens instead?

**Comment by red4stone** [comment]
Having a similar issue-
OS: Ubuntu noble 24.04 x86_64
The script appears to work fine at first, making a tab in the script menu to add formatting codes and such, but when actually saving files it just uses whatever data is set in the default obs file-naming textbox.

**Comment by Penwy** [comment]
that's normal, as described on the script's page, replay buffer functionalities are not currently available on vanilla obs, and require the provided custom build to work

**Comment by Penwy** [comment]
Closing from lack of followup of original poster.
